trainingInput:
  region: europe-west1
  scaleTier: BASIC
  masterConfig:
    imageUri: eu.gcr.io/gothic-parsec-308513/trainer_image:latest
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 2
    maxParallelTrials: 1
    hyperparameterMetricTag: f1-score
    enableTrialEarlyStopping: TRUE
    params:
      - parameterName: n_estimators
        type: INTEGER
        minValue: 50
        maxValue: 1000
        scaleType: UNIT_LINEAR_SCALE
      - parameterName: learning_rate
        type: DOUBLE
        minValue: 0.0001
        maxValue: 0.5
        scaleType: UNIT_LOG_SCALE
      - parameterName: scale_pos_weight
        type: CATEGORICAL
        categoricalValues:
          - "TRUE"
          - "FALSE"
